# Sep 8th. 2022

I had forgotten that ~1800 fields in the ground-truth table used to train MLs included labels from non-experts. Non-experts had done 2 rounds of labeling. 

**Recall:** In the second round I had listed the links on Google Sheets on the second tab and that misled Michael Brady.

The list of labels that includes non-experts' votes are on OneDrive.

```train_labels.csv``` that include ~1800 fields in it is generated by ```Form_GroundTruth_Labels_experts_and_NESet2.ipynb```

In [1]:
import pandas as pd
import numpy as np

import os, os.path
import sys

In [2]:
param_dir = "/Users/hn/Documents/01_research_data/NASA/parameters/"
NE_S2_dir = param_dir + "nonExpert_set2_fields/"
Perry_and_Co_dir = "/Users/hn/Documents/01_research_data/NASA/Perry_and_Co/"
ML_data_dir = "/Users/hn/Documents/01_research_data/NASA/ML_data/"

In [3]:
train_labels=pd.read_csv(ML_data_dir + "train_labels.csv")
train_labels.shape

(1849, 2)

In [4]:
print('Length of train_labels.ID is [{}].'.format(len(train_labels.ID)))
print('Length of unique train_labels.ID is [{}].'.format(len(train_labels.ID.unique())))

Length of train_labels.ID is [1849].
Length of unique train_labels.ID is [1849].

In [5]:
# expert_set1_postmeeting_consensus=pd.read_csv(ML_data_dir+"expert_set1_postmeeting_consensus.csv")
# expert_set1_premeeting_consensus=pd.read_csv(ML_data_dir+"expert_set1_premeeting_consensus.csv")
# expert_set2_premeeting_consensus=pd.read_csv(ML_data_dir+"expert_set2_premeeting_consensus.csv")

# print(len(expert_set1_postmeeting_consensus.ID.unique()))
# print(len(expert_set1_premeeting_consensus.ID.unique()))
# print(len(expert_set2_premeeting_consensus.ID.unique()))

# set1_all_votes=pd.read_csv(Perry_and_Co_dir+"set1_all_votes.csv")
# set2_all_responases_noRepetition=pd.read_csv(Perry_and_Co_dir+"set2_all_responases_noRepetition.csv")

# print (len(set1_all_votes.ID))
# print (len(set1_all_votes.ID.unique()))

# print (len(set2_all_responases_noRepetition.ID))
# print (len(set2_all_responases_noRepetition.ID.unique()))

# set1_2=pd.concat([set1_all_votes, set2_all_responases_noRepetition])
# print (len(set1_2.ID))
# print (len(set1_2.ID.unique()))

# set2_all_responses=pd.read_csv(Perry_and_Co_dir+"set2_all_responses.csv")
# set1_2=pd.concat([set1_all_votes, set2_all_responses])
# print (len(set1_2.ID))
# print (len(set1_2.ID.unique()))

In [11]:
NE_S2_dir = "/Users/hn/Documents/01_research_data/NASA/parameters/nonExpert_set2_fields/"
f_name = "NE_set2_post_expert_meeting_IDs_Votes_IncludesNA_fromOneDrive_May23.csv"
NE_S2_postExpertMeeting=pd.read_csv(NE_S2_dir+ f_name)

NE_S2_postExpertMeeting=NE_S2_postExpertMeeting[["ID", "HosseinV"]]
NE_S2_postExpertMeeting=NE_S2_postExpertMeeting[NE_S2_postExpertMeeting.HosseinV.isin(["Single", "Double"])]

print (len(NE_S2_postExpertMeeting.ID.unique()))
print (NE_S2_postExpertMeeting.shape)
NE_S2_postExpertMeeting.head(2)

1415
(1415, 2)

                    ID HosseinV
0  101534_WSDA_SF_2018   Single
1  108118_WSDA_SF_2017   Single

In [12]:
NE_S2_postExpertMeeting=NE_S2_postExpertMeeting.iloc[:, 0:2]
NE_S2_postExpertMeeting.head(2)

                    ID HosseinV
0  101534_WSDA_SF_2018   Single
1  108118_WSDA_SF_2017   Single

In [14]:
NE_S2_postExpertMeeting = NE_S2_postExpertMeeting[~NE_S2_postExpertMeeting.ID.isin(list(train_labels))]
NE_S2_postExpertMeeting.shape

(1415, 2)

In [16]:
evaluation_set=pd.read_csv(param_dir+"evaluation_set.csv")
print (evaluation_set.shape)
evaluation_set.head(2)

(6340, 8)

,ID,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county
0,100010_WSDA_SF_2017,alfalfa hay,center pivot,wsda,34,34.310305,2017/09/12,Grant
1,100204_WSDA_SF_2017,alfalfa hay,center pivot,wsda,62,61.826535,2017/08/09,Grant

In [17]:
NE_S2_postExpertMeeting= pd.merge(NE_S2_postExpertMeeting, evaluation_set, on=['ID'], how='left')

In [18]:
sorted(NE_S2_postExpertMeeting.CropTyp.unique())

['barley',
 'barley hay',
 'bean, dry',
 'bean, green',
 'bluegrass seed',
 'buckwheat',
 'canola',
 'carrot',
 'corn seed',
 'corn, field',
 'corn, sweet',
 'grass hay',
 'grass seed',
 'market crops',
 'mint',
 'oat hay',
 'onion',
 'pea seed',
 'pea, dry',
 'pea, green',
 'potato',
 'triticale',
 'wheat',
 'yellow mustard']

In [32]:
# NE_set2_premeeting_Consensus=pd.read_csv(param_dir + "nonExpert_set2_fields/" +  "NE_set2_premeeting_Consensus.csv")
# NE_set2_premeeting_Consensus_IDs_Votes_IncludesUnsure = pd.read_csv(param_dir + "nonExpert_set2_fields/" + 
#                                                     "NE_set2_premeeting_Consensus_IDs_Votes_IncludesUnsure.csv")

# print (NE_set2_premeeting_Consensus.shape)
# print (NE_set2_premeeting_Consensus_IDs_Votes_IncludesUnsure.shape)

## Already Created PDF of Non-Expert Survey 2.

### This is created in "NE_set_2_analysis.ipynb"

# NE easy Crops

- **Read 6000 fields**
- **Toss Small fields**
- **Toss NE Set 2**
- **Toss Expert Set 1 and 2**
- **List goddamn Agreements**
- **List 75% Agreements**
- **List the rest**

# Read 6000 fields.

In [53]:
evaluation_set=pd.read_csv(param_dir+"evaluation_set.csv")
print (len(evaluation_set.ID.unique()), ",", evaluation_set.shape[0])

6340 , 6340

# Read Non-Expert Survey 2. Some fields are less than 10 acres!!!!

In [54]:
f_name = "NE_set2_post_expert_meeting_IDs_Votes_IncludesNA_fromOneDrive_May23.csv"
NE_S2_postExpertMeeting=pd.read_csv(NE_S2_dir+ f_name)

NE_S2_postExpertMeeting=NE_S2_postExpertMeeting[["ID", "HosseinV"]]
NE_S2_postExpertMeeting=NE_S2_postExpertMeeting[NE_S2_postExpertMeeting.HosseinV.isin(["Single", "Double"])]
NE_S2_postExpertMeeting=pd.merge(NE_S2_postExpertMeeting, evaluation_set, on=['ID'], how='left')
print (len(NE_S2_postExpertMeeting.ID.unique()), "," , NE_S2_postExpertMeeting.shape[0])
NE_S2_postExpertMeeting.head(2)

1415 , 1415

,ID,HosseinV,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county
0,101534_WSDA_SF_2018,Single,barley,center pivot,wsda,3,3.220729,2018/08/14 00:00:00,Franklin
1,108118_WSDA_SF_2017,Single,barley,rill,wsda,5,4.956565,2017/07/12,Grant

In [55]:
NE_S2_postExpertMeeting[NE_S2_postExpertMeeting.ExctAcr<=10].shape

(401, 9)

# Expert and Non-Expert votes in train set

In [56]:
train_labels=pd.read_csv(ML_data_dir + "train_labels.csv")
train_labels=pd.merge(train_labels, evaluation_set, on=['ID'], how='left')
train_labels.shape

(1849, 9)

In [57]:
train_labels[train_labels.ExctAcr<=10].shape

(507, 9)

### Toss Small fields

In [58]:
evaluation_set=evaluation_set[evaluation_set.ExctAcr>10].copy()
print (len(evaluation_set.ID.unique()),",", evaluation_set.shape[0])

3539 , 3539

### Toss NE Set 2

In [59]:
evaluation_set=evaluation_set[~evaluation_set.ID.isin(list(NE_S2_postExpertMeeting.ID.unique()))].copy()
evaluation_set.shape

(2525, 8)

In [60]:
train_labels_expert = train_labels[~train_labels.ID.isin(list(NE_S2_postExpertMeeting.ID.unique()))]
train_labels_Nonexpert = train_labels[train_labels.ID.isin(list(NE_S2_postExpertMeeting.ID.unique()))]

print (train_labels_expert.shape)
print (train_labels_Nonexpert.shape)

(434, 9)
(1415, 9)

### Toss Expert Set 1 and 2

In [61]:
evaluation_set=evaluation_set[~evaluation_set.ID.isin(list(train_labels.ID.unique()))].copy()
evaluation_set.shape

(2197, 8)

In [62]:
evaluation_set_minusTrainLabels=evaluation_set.copy()

In [63]:
# nonExpert_2605_votes=pd.read_csv(param_dir + "nonExpert_2605_votes.csv")
# nonExpert_2605_votes.shape

# nonExpert_2605_votes[nonExpert_2605_votes.ID.isin(list(train_labels.ID))].shape
# nonExpert_2605_votes.ExctAcr.min()

# nonExpert_2605_votes= nonExpert_2605_votes[~nonExpert_2605_votes.ID.isin(list(train_labels.ID))]
# nonExpert_2605_votes.shape
# evaluation_set[evaluation_set.ID.isin(list(nonExpert_2605_votes.ID.unique()))].shape
# nonExpert_2605_votes[nonExpert_2605_votes.ID.isin(train_labels_Nonexpert.ID.unique())].shape
# A = evaluation_set[~evaluation_set.ID.isin(list(nonExpert_2605_votes.ID.unique()))].copy()
# B = evaluation_set[evaluation_set.ID.isin(list(nonExpert_2605_votes.ID.unique()))].copy()
# print (evaluation_set[evaluation_set.ID.isin(list(nonExpert_2605_votes.ID.unique()))].shape)
# print (evaluation_set[~evaluation_set.ID.isin(list(nonExpert_2605_votes.ID.unique()))].shape)
# print (nonExpert_2605_votes[nonExpert_2605_votes.ID.isin(list(evaluation_set.ID.unique()))].shape)
# print (nonExpert_2605_votes[~nonExpert_2605_votes.ID.isin(list(evaluation_set.ID.unique()))].shape)

# Read 6000 Responses Carefully. 
What we have below is copies from ```6000_nonExpert_VoteCount```

In [64]:
import pandas as pd
import csv

import os, os.path
import sys

In [65]:
param_dir = "/Users/hn/Documents/01_research_data/NASA/parameters/"

In [66]:
choices_xl = pd.ExcelFile(param_dir + "all_extended.xlsx")
choices_sheet_names = choices_xl.sheet_names  # see all sheet names

response_set_1_xl = pd.ExcelFile(param_dir + "6000responses.xlsx")
response_sheet_names = response_set_1_xl.sheet_names  # see all sheet names

print (choices_sheet_names[:5])
print (response_sheet_names[:5])

['extended_1', 'extended_2', 'extended_3', 'extended_4', 'extended_5']
['Set 1 E', 'Set 2 E', 'Set 3 E', 'Set 4 E', 'Set 5 E']

In [67]:
evaluation_set_csv = pd.read_csv(param_dir + "evaluation_set.csv")
evaluation_set_csv.drop(labels=["ExctAcr"], axis='columns', inplace=True)

print (len(evaluation_set_csv.ID))
print (len(evaluation_set_csv.ID.unique()))

6340
6340

# Read and assemble the choices; i.e. selected fields for survey

In [68]:
survey_fields = pd.DataFrame()
for a_sheet in choices_sheet_names:
    a_choice_sheet = choices_xl.parse(a_sheet)
    survey_fields = pd.concat([survey_fields, a_choice_sheet])

print (survey_fields.shape)
survey_fields.drop(labels=["ExctAcr"], axis='columns', inplace=True)
print (len(survey_fields.ID))
print (len(survey_fields.ID.unique()))

survey_fields_help = survey_fields.copy()
survey_fields_help = survey_fields_help[evaluation_set_csv.columns].copy()

survey_fields_help.sort_values(by=['ID'], inplace=True)
evaluation_set_csv.sort_values(by=['ID'], inplace=True)

survey_fields_help.reset_index(inplace=True, drop=True)
evaluation_set_csv.reset_index(inplace=True, drop=True)

evaluation_set_csv.equals(survey_fields_help)

(6340, 17)
6340
6340

True

In [69]:
evaluation_set_csv.head(2)

,ID,CropTyp,Irrigtn,DataSrc,Acres,LstSrvD,county
0,100010_WSDA_SF_2017,alfalfa hay,center pivot,wsda,34,2017/09/12,Grant
1,100018_WSDA_SF_2017,apple,drip,wsda,7,2017/05/03,Grant

## Count number of questions

In [70]:
question_count = 0

for a_choice_sheet in choices_sheet_names:
    
    # read a damn sheet
    a_choice_sheet = choices_xl.parse(a_choice_sheet)

    # add them to the damn list
    question_count += a_choice_sheet.shape[0]

print('There are [{ques_count}] questions.'.format(ques_count=question_count))

There are [6340] questions.

# Clean Vote count start here:

#### Problems:
 - In the beginning emails were not collected! (mostly alfalfa and apple?)
 - There are some Forms that I still do not have access to. Eshwar has not transferred them to Google Drive despite repeated emails.
 - There are forms with repeated answers and no email.
 - Min has responded sparsley, mostly no email, and problematic forms. 
 - Different email for Hossein. Since I was receiving emails after completing forms, I used a fake email!! no, thank you!
 - Problematic forms were responded by some, and after fix by others. Drop these forms. No, we can read also problematic forms and keep the latest responses. This way we have Kirti's latest responses and Supriya's responses from Problematic forms.
 - Not much Mike's vote in wheat.

In [147]:
## Define the damn NE_Survey1_response dataframe
NE_Survey1_response = pd.DataFrame(columns=['Form', 'Question', 'ID',
                                            "Hossein", "Supriya", "Kirti", "Mike", "Min"], 
                                   index=range(question_count))
NE_Survey1_response.head(1)
curr_row = 0

extended_choices = pd.DataFrame()

###### populate the NE_Survey1_response datafrme

for response_sheet_name in response_sheet_names:
    # If "problem" in the name of sheet, pass:  
    # No, we can read also problematic forms and keep the latest responses. 
    # This way we have Kirti's latest responses and Supriya's responses from Problematic forms.
    #
    #   IF Kirti responded to a problematic sheet, and then to fixed sheet,
    #   Then we have duplicates!!!!!
    #
    # if 'problem' in response_sheet_name.lower():
    #     continue

    # pick up the numeric part of the sheet names
    sheet_numeric_part = response_sheet_name.split()[1]
    
    # Form sheet names of choices excel sheets
    choice_sheet_name = "extended_" + sheet_numeric_part
    
    a_choice_sheet = choices_xl.parse(choice_sheet_name)
    a_response_sheet = response_set_1_xl.parse(response_sheet_name)

    # If no email is recoded, pass. We do not want it
    # a_response_sheet['Email Address'].isnull().any() works as well. 
    # It is an indication that the form did not collect emails! One or all!
    if a_response_sheet['Email Address'].isnull().all():
        continue

    
    # Fix Hossein email. (replace emails by names!)
    a_response_sheet['Email Address'] = a_response_sheet['Email Address'].str.lower()

    a_response_sheet.loc[a_response_sheet['Email Address'].str.contains('noorazar', na=False), 
                         'Email Address']="Hossein"

    a_response_sheet.loc[a_response_sheet['Email Address'].str.contains('kirti', na=False), 
                         'Email Address']="Kirti"

    a_response_sheet.loc[a_response_sheet['Email Address'].str.contains('supriya', na=False), 
                         'Email Address']="Supriya"

    a_response_sheet.loc[a_response_sheet['Email Address'].str.contains('brady', na=False), 
                         'Email Address']="Mike"

    a_response_sheet.loc[a_response_sheet['Email Address'].str.contains('ming', na=False), 
                         'Email Address']="Min"

    # Fix repeated Kirti in one sheet
    #
    #   IF Kirti responded to a problematic sheet, and then responded to the fixed sheet,
    #   Then we have duplicates!!!!!
    #
    latest_Kirti = a_response_sheet[a_response_sheet['Email Address']=="Kirti"].Timestamp.max()
    Kirti = a_response_sheet[a_response_sheet['Email Address']=="Kirti"]
    # The fact that we have "<" below, eliminates to count how many times
    # Kirti has responded. i.e. if there is one response, it will not be dropped!
    bad_index = Kirti[Kirti.Timestamp < latest_Kirti].index
    a_response_sheet.drop(bad_index, inplace=True)

    latest_Hossein = a_response_sheet[a_response_sheet['Email Address']=="Hossein"].Timestamp.max()
    Hossein = a_response_sheet[a_response_sheet['Email Address']=="Hossein"]
    # The fact that we have "<" below, eliminates to count how many times
    # Kirti has responded. i.e. if there is one response, it will not be dropped!
    bad_index = Hossein[Hossein.Timestamp < latest_Hossein].index
    a_response_sheet.drop(bad_index, inplace=True)
    
    
    latest_Supriya = a_response_sheet[a_response_sheet['Email Address']=="Supriya"].Timestamp.max()
    Supriya = a_response_sheet[a_response_sheet['Email Address']=="Supriya"]
    # The fact that we have "<" below, eliminates to count how many times
    # Kirti has responded. i.e. if there is one response, it will not be dropped!
    bad_index = Supriya[Supriya.Timestamp < latest_Supriya].index
    a_response_sheet.drop(bad_index, inplace=True)
    
    latest_Mike = a_response_sheet[a_response_sheet['Email Address']=="Mike"].Timestamp.max()
    Mike = a_response_sheet[a_response_sheet['Email Address']=="Mike"]
    # The fact that we have "<" below, eliminates to count how many times
    # Kirti has responded. i.e. if there is one response, it will not be dropped!
    bad_index = Mike[Mike.Timestamp < latest_Mike].index
    a_response_sheet.drop(bad_index, inplace=True)
    
    latest_Min = a_response_sheet[a_response_sheet['Email Address']=="Min"].Timestamp.max()
    Min = a_response_sheet[a_response_sheet['Email Address']=="Min"]
    # The fact that we have "<" below, eliminates to count how many times
    # Kirti has responded. i.e. if there is one response, it will not be dropped!
    bad_index = Min[Min.Timestamp < latest_Min].index
    a_response_sheet.drop(bad_index, inplace=True)

    if len(a_response_sheet['Email Address']) != len(a_response_sheet['Email Address'].unique()):
        raise ValueError("Something is wrong in email address column")

    # If less than or equal to 2 people responsed, pass. Keep it if 3 people has responded
    # I commented out the following, since some 
    # fucking sheets had problem. So, some people responded to it, but
    # did not respond to fixed Form. And I want to keep as much as possible!
    # i.e. I will keep the problematic forms and keep whatever questions in them.
    # if len(a_response_sheet['Email Address'])<=2:
    #     continue
    
    #
    # drop unwanted opinions, i.e. keep experts opinions
    #
    # a_response_sheet = a_response_sheet[~(a_response_sheet["Email Address"]=="Min")].copy()
    
    for a_col_name in a_response_sheet.columns:
        if "http" in a_col_name:
            question_number = a_col_name.split()[1].split(":")[0]
            currnt_ID = a_choice_sheet.loc[int(question_number)-1, "ID"]
            if currnt_ID in list(NE_Survey1_response.ID):
                curr_idx = NE_Survey1_response[NE_Survey1_response.ID == currnt_ID].index
                
                if "Hossein" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_idx, "Hossein"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Hossein"][a_col_name].values[0]

                if "Supriya" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_idx, "Supriya"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Supriya"][a_col_name].values[0]

                if "Kirti" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_idx, "Kirti"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Kirti"][a_col_name].values[0]
                if "Mike" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_idx, "Mike"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Mike"][a_col_name].values[0]
                
                if "Min" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_idx, "Min"]=a_response_sheet[a_response_sheet["Email Address"] == \
                                                                     "Min"][a_col_name].values[0]
            else:
                NE_Survey1_response.loc[curr_row, "ID"] = currnt_ID
                NE_Survey1_response.loc[curr_row, "Form"] = int(sheet_numeric_part)
                NE_Survey1_response.loc[curr_row, "Question"] = int(question_number)
                
                if "Hossein" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_row, "Hossein"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Hossein"][a_col_name].values[0]

                if "Supriya" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_row, "Supriya"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Supriya"][a_col_name].values[0]

                if "Kirti" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_row, "Kirti"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Kirti"][a_col_name].values[0]
                if "Mike" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_row, "Mike"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Mike"][a_col_name].values[0]
                
                if "Min" in list(a_response_sheet["Email Address"]):
                    NE_Survey1_response.loc[curr_row, "Min"]=a_response_sheet[a_response_sheet["Email Address"]==\
                                                                     "Min"][a_col_name].values[0]
                curr_row += 1

In [148]:
print (NE_Survey1_response.shape)
NE_Survey1_response.head(2)

(6340, 8)

,Form,Question,ID,Hossein,Supriya,Kirti,Mike,Min
0,1,1,104119_WSDA_SF_2016,Single Crop,Single Crop,Single Crop,Single Crop,Single Crop
1,1,2,51403_WSDA_SF_2016,Single Crop,Single Crop,Single Crop,Single Crop,Unsure

#### Email was not collected for 10 Forms. Drop them.

all alfalfa.

In [149]:
NE_Survey1_response_noNA = NE_Survey1_response.dropna(how='all', axis='rows');

In [150]:
NE_Survey1_response_noNA.shape

(5740, 8)

In [151]:
missing_from_responses = evaluation_set_csv[~(evaluation_set_csv.ID.isin(list(NE_Survey1_response_noNA.ID)))].copy()
print (missing_from_responses.shape)

missing_from_responses.head(5)

(600, 7)

,ID,CropTyp,Irrigtn,DataSrc,Acres,LstSrvD,county
0,100010_WSDA_SF_2017,alfalfa hay,center pivot,wsda,34,2017/09/12,Grant
23,100204_WSDA_SF_2017,alfalfa hay,center pivot,wsda,62,2017/08/09,Grant
24,100214_WSDA_SF_2017,alfalfa hay,center pivot,wsda,13,2017/08/28,Grant
25,100217_WSDA_SF_2017,alfalfa hay,center pivot,wsda,137,2017/09/06,Grant
31,100260_WSDA_SF_2017,alfalfa hay,center pivot,wsda,81,2017/09/19,Grant

In [152]:
missing_from_responses.tail(5)

,ID,CropTyp,Irrigtn,DataSrc,Acres,LstSrvD,county
6301,99656_WSDA_SF_2017,alfalfa hay,center pivot,wsda,144,2017/04/19,Grant
6302,99681_WSDA_SF_2017,alfalfa hay,center pivot,wsda,14,2017/06/21,Grant
6309,99742_WSDA_SF_2017,alfalfa hay,center pivot,wsda,135,2017/09/11,Grant
6312,99765_WSDA_SF_2017,alfalfa hay,center pivot,wsda,1,2017/07/12,Grant
6318,99799_WSDA_SF_2017,alfalfa hay,center pivot,wsda,55,2017/08/09,Grant

In [154]:
NE_Survey1_response.dropna(how='all', axis='rows', inplace=True);
NE_Survey1_response.shape

(5740, 8)

# Correct the damn responses

1. We have not been consistent in the Forms!
2. The options we gave there was horrible. For example, the options were:
   - Single Crop
   - Double Crop
   - Unsure
   - Other:
   
Convert anything that has ```cover```, ```mustard``` in it to ```double-crop```, single crops are single crops, anything else will be ```Unsure```.

If an answer has any of these pairs in it, it will be labeled as unsure ```[single, double]```, ```[single, cover]```,
```[single, mustard]```.

In [155]:
NE_Survey1_response.Supriya.unique()

array(['Single Crop', 'Double Crop',
       'May be mustard growing here second curve from aug-sept onwards',
       'may be mustard',
       'May be non-mustard cover crop suggested by second curve',
       'Looks like a non-mustard cover crop', 'Double Crop/Cover crop',
       nan, 'Unsure'], dtype=object)

In [156]:
NE_Survey1_response.reset_index(inplace=True, drop=True)

In [157]:
people = ["Hossein", "Supriya", "Kirti", "Mike", "Min"]

# We need to keep "none" so that we can use it to compute
# majority vote where someone has not responded a Form
NE_Survey1_response[people] = NE_Survey1_response[people].fillna('none')

for idx in NE_Survey1_response.index:
    for person in people:
        if NE_Survey1_response.loc[idx, person] in ["Single Crop", "Double Crop", "Unsure", "none"]:
            continue
            
        if "cover" in NE_Survey1_response.loc[idx, person].lower() or \
           "mustard" in NE_Survey1_response.loc[idx, person].lower():
            NE_Survey1_response.loc[idx, person] = "Double Crop"
        else:
            NE_Survey1_response.loc[idx, person] = "Unsure"
            
NE_Survey1_response.Supriya.unique()

array(['Single Crop', 'Double Crop', 'none', 'Unsure'], dtype=object)

## Drop Min

In [158]:
NE_Survey1_response.drop(labels=["Min"], axis="columns", inplace=True)
people = ["Hossein", "Supriya", "Kirti", "Mike"]

In [159]:
NE_Survey1_response.tail(5)

,Form,Question,ID,Hossein,Supriya,Kirti,Mike
5735,106,36,104188_WSDA_SF_2017,Unsure,Double Crop,Unsure,none
5736,106,37,106509_WSDA_SF_2017,Single Crop,Double Crop,Double Crop,none
5737,106,38,108383_WSDA_SF_2017,Single Crop,Single Crop,Double Crop,none
5738,106,39,98716_WSDA_SF_2017,Unsure,Double Crop,Double Crop,none
5739,106,40,99604_WSDA_SF_2017,Unsure,Single Crop,Double Crop,none

In [164]:
print (evaluation_set.shape)
evaluation_set.head(2)

(2197, 8)

,ID,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county
0,100010_WSDA_SF_2017,alfalfa hay,center pivot,wsda,34,34.310305,2017/09/12,Grant
1,100204_WSDA_SF_2017,alfalfa hay,center pivot,wsda,62,61.826535,2017/08/09,Grant

In [168]:
print (NE_Survey1_response.shape)
print (NE_Survey1_response[NE_Survey1_response.ID.isin(list(evaluation_set.ID))].shape)

(5740, 7)

In [183]:
evaluation_set[~evaluation_set.ID.isin(list(NE_Survey1_response.ID))]

,ID,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county
0,100010_WSDA_SF_2017,alfalfa hay,center pivot,wsda,34,34.310305,2017/09/12,Grant
1,100204_WSDA_SF_2017,alfalfa hay,center pivot,wsda,62,61.826535,2017/08/09,Grant
2,100214_WSDA_SF_2017,alfalfa hay,center pivot,wsda,13,13.105399,2017/08/28,Grant
3,100217_WSDA_SF_2017,alfalfa hay,center pivot,wsda,137,137.454836,2017/09/06,Grant
4,100260_WSDA_SF_2017,alfalfa hay,center pivot,wsda,81,80.562199,2017/09/19,Grant
...,...,...,...,...,...,...,...,...
870,108232_WSDA_SF_2018,apple,sprinkler,wsda,25,25.386136,2018/09/01 00:00:00,Franklin
873,108366_WSDA_SF_2018,apple,sprinkler,wsda,24,24.191089,2018/05/30 00:00:00,Franklin
874,108367_WSDA_SF_2018,apple,sprinkler,wsda,28,27.722180,2018/11/06 00:00:00,Franklin
875,108380_WSDA_SF_2018,apple,drip,wsda,26,26.394685,2018/06/06 00:00:00,Franklin
878,108412_WSDA_SF_2018,apple,micro-sprinkler,wsda,16,16.413447,2018/06/06 00:00:00,Franklin

In [ ]:
print (evaluation_set.shape)
print (evaluation_set[evaluation_set.ID.isin(list(missing_from_responses.ID))].shape)
print (1817+380)

In [193]:
NE_Survey1_response=NE_Survey1_response[NE_Survey1_response.ID.isin(list(evaluation_set.ID.unique()))].copy()
NE_Survey1_response=pd.merge(NE_Survey1_response, evaluation_set, on=['ID'], how='left')
print (NE_Survey1_response.shape)
NE_Survey1_response.head(2)

(1817, 14)

,Form,Question,ID,Hossein,Supriya,Kirti,Mike,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county
0,1,1,104119_WSDA_SF_2016,Single Crop,Single Crop,Single Crop,Single Crop,alfalfa hay,center pivot,wsda,26,26.413875,2016/08/17 00:00:00,Adams
1,1,4,51576_WSDA_SF_2016,Single Crop,Single Crop,Single Crop,Single Crop,alfalfa hay,center pivot,wsda,68,67.841870,2016/07/20 00:00:00,Adams

In [202]:
(sorted(NE_Survey1_response.CropTyp.unique()))

['alfalfa hay',
 'apple',
 'apricot',
 'asparagus',
 'barley hay',
 'bean, dry',
 'bean, green',
 'blueberry',
 'bluegrass seed',
 'buckwheat',
 'canola',
 'carrot seed',
 'cherry',
 'corn, field',
 'corn, sweet',
 'fallow',
 'fallow, idle',
 'fallow, tilled',
 'fescue seed',
 'grape, juice',
 'grape, wine',
 'grass seed',
 'hops',
 'medicinal herb',
 'mustard',
 'nectarine/peach',
 'onion seed',
 'orchard, unknown',
 'pasture',
 'pea, dry',
 'pear',
 'pepper',
 'plum',
 'poplar',
 'potato',
 'pumpkin',
 'ryegrass seed',
 'sod farm',
 'squash',
 'sudangrass',
 'sugar beet',
 'sugar beet seed',
 'sunflower',
 'sunflower seed',
 'timothy',
 'triticale',
 'triticale hay',
 'unknown',
 'watermelon',
 'wheat',
 'wheat fallow',
 'wildlife feed',
 'yellow mustard']

In [212]:
# A=pd.read_csv(param_dir+"evaluation_set.csv")
# sorted(A.CropTyp.unique())

# Check Check Check 
   **1.  Check Acreage.**
   
   **2. Toss Experts and non-experts labels that we already have.**
   
   **3. Focus on Easy crops only.**

In [211]:
# the following list is from the Excel file called "PerrysChoices.xlsx" in
hard_crops = ['bean, dry', 'bean, green', 'buckwheat', 'canola', 
              'carrot', 'triticale', 'market crops', 'grass hay',
              'mint', 'onion', 'barley', 'barley hay',
              'oat hay', 'yellow mustard',
              'corn seed', 'corn, field','corn, sweet',
              'wheat','potato', 'alfalfa seed', 'grass seed', 'bluegrass seed',
              'pea, dry', 'pea, green']
len(hard_crops)

24

In [214]:
NE_Survey1_response.ExctAcr.min()

10.0052556916053

In [217]:
NE_Survey1_response[NE_Survey1_response.ID.isin(list(train_labels.ID.unique()))].shape

(0, 14)

In [221]:
NE_Survey1_response.shape

(1817, 14)

In [227]:
(NE_Survey1_response.groupby(['CropTyp'])['CropTyp'].count())

CropTyp
alfalfa hay          43
apple               543
apricot              16
asparagus            23
barley hay            1
bean, dry             1
bean, green           2
blueberry            24
bluegrass seed       10
buckwheat             2
canola                5
carrot seed          15
cherry              106
corn, field           3
corn, sweet           5
fallow               31
fallow, idle         22
fallow, tilled       21
fescue seed           9
grape, juice         71
grape, wine         128
grass seed            2
hops                120
medicinal herb        8
mustard               2
nectarine/peach      18
onion seed            8
orchard, unknown      9
pasture             141
pea, dry              1
pear                 31
pepper                4
plum                  4
poplar               44
potato                1
pumpkin               9
ryegrass seed         8
sod farm             15
squash                9
sudangrass           37
sugar beet           10
sugar beet seed      17
sunflower             7
sunflower seed       29
timothy              72
triticale             2
triticale hay        16
unknown              31
watermelon           10
wheat                 1
wheat fallow         41
wildlife feed        27
yellow mustard        2
Name: CropTyp, dtype: int64

# Compute Majority and Final Votes

This is where I diverge from ```6000_nonExpert_VoteCount```. I want to see where there
are absolute consensus and where there are 75% consensus.

In [269]:
NE_FinalSurvey = NE_Survey1_response.copy()
NE_FinalSurvey.drop(["Form", "Question"],  axis="columns", inplace=True)
NE_FinalSurvey.reset_index(inplace=True, drop=True)

In [270]:
import collections

idx=3

answers_set = collections.Counter(NE_FinalSurvey.loc[idx, people].values)
print (answers_set)

print ("---------------------------------------------------------------------------")
print ("Hossein's unique votes are", NE_FinalSurvey.Hossein.unique())
print ("Supriya's unique votes are", NE_FinalSurvey.Supriya.unique())
print ("Mike's unique votes are", NE_FinalSurvey.Mike.unique())
print ("Kirti's unique votes are", NE_FinalSurvey.Kirti.unique())

print ("Kirti's count of None answers is ",NE_FinalSurvey[NE_FinalSurvey.Kirti=="none"].shape[0])
print ("Mike's count of None answers is ", NE_FinalSurvey[NE_FinalSurvey.Mike=="none"].shape[0])

print ("---------------------------------------------------------------------------")
(NE_FinalSurvey.loc[idx, people])

Counter({'Double Crop': 3, 'Unsure': 1})
---------------------------------------------------------------------------
Hossein's unique votes are ['Single Crop' 'Double Crop' 'none' 'Unsure']
Supriya's unique votes are ['Single Crop' 'Double Crop' 'none']
Mike's unique votes are ['Single Crop' 'Double Crop' 'Unsure' 'none']
Kirti's unique votes are ['Single Crop' 'Unsure' 'none' 'Double Crop']
Kirti's count of None answers is  33
Mike's count of None answers is  109
---------------------------------------------------------------------------

Hossein    Double Crop
Supriya    Double Crop
Kirti           Unsure
Mike       Double Crop
Name: 3, dtype: object

# Convert Unsure to None

In [271]:
NE_FinalSurvey.loc[NE_FinalSurvey.Hossein == 'Unsure', 'Hossein']='none'
NE_FinalSurvey.loc[NE_FinalSurvey.Supriya == 'Unsure', 'Supriya']='none'
NE_FinalSurvey.loc[NE_FinalSurvey.Mike == 'Unsure', 'Mike']='none'
NE_FinalSurvey.loc[NE_FinalSurvey.Kirti == 'Unsure', 'Kirti']='none'

In [272]:
print ("---------------------------------------------------------------------------")
print ("Hossein's unique votes are", len(NE_FinalSurvey.Hossein.unique()))
print ("Supriya's unique votes are", len(NE_FinalSurvey.Supriya.unique()))
print ("Mike's unique votes are", len(NE_FinalSurvey.Mike.unique()))
print ("Kirti's unique votes are", len(NE_FinalSurvey.Kirti.unique()))

---------------------------------------------------------------------------
Hossein's unique votes are 3
Supriya's unique votes are 3
Mike's unique votes are 3
Kirti's unique votes are 3

In [432]:
# NE_FinalSurvey = NE_Survey1_response.copy()
# NE_FinalSurvey.drop(["Form", "Question"],  axis="columns", inplace=True)
# NE_FinalSurvey.reset_index(inplace=True, drop=True)

# NE_FinalSurvey.loc[NE_FinalSurvey.Hossein == 'Unsure', 'Hossein']='none'
# NE_FinalSurvey.loc[NE_FinalSurvey.Supriya == 'Unsure', 'Supriya']='none'
# NE_FinalSurvey.loc[NE_FinalSurvey.Mike == 'Unsure', 'Mike']='none'
# NE_FinalSurvey.loc[NE_FinalSurvey.Kirti == 'Unsure', 'Kirti']='none'


# NE_FinalSurvey["Vote"] = "PlaceHolder"

# for idx in NE_FinalSurvey.index:
#     if len(NE_FinalSurvey.loc[idx, people].unique())==1:
#         NE_FinalSurvey.loc[idx, "Vote"]=NE_FinalSurvey.loc[idx, people].unique()[0]+" (absolute consensus)" 
#     else:
#         answers_set=collections.Counter(NE_FinalSurvey.loc[idx, people].values)
#         if answers_set['none']==1:
#             del answers_set['none']
#             if len(answers_set)==1:
#                 NE_FinalSurvey.loc[idx, "Vote"]= list(answers_set.keys())[0]+" (3 consensus - 1 none)"
#             elif len(answers_set)>1:
#                 NE_FinalSurvey.loc[idx, "Vote"]="2 agree - 1 disagree - 1 none"
#         else:
#             NE_FinalSurvey.loc[idx, "Vote"]="disagreement"
            
# NE_FinalSurvey.head(2)

In [434]:
# sorted (NE_FinalSurvey.Vote.unique())

In [433]:
#NE_FinalSurvey.groupby(['Vote'])['Vote'].count()

In [436]:
# NE_FinalSurvey.shape

In [437]:
1394+15

1409

In [438]:
# NE_FinalSurvey.Hossein.unique()

In [347]:
#     valid_votes = NE_FinalSurvey.loc[idx, people].values != 'none'
#     valid_votes = NE_FinalSurvey.loc[idx, people].values[valid_votes]

#     needed_vote_count = np.floor(len(valid_votes)/2)+1
#     valid_votes_freq = collections.Counter(valid_votes)

#     for key, value in valid_votes_freq.items():
#         if value>=needed_vote_count:
#             NE_FinalSurvey.loc[idx, "Vote"] = key
            
# NE_Survey1_response.head(2)

In [425]:
NE_FinalSurvey = NE_Survey1_response.copy()
NE_FinalSurvey.drop(["Form", "Question"],  axis="columns", inplace=True)
NE_FinalSurvey.reset_index(inplace=True, drop=True)

NE_FinalSurvey.loc[NE_FinalSurvey.Hossein == 'Unsure', 'Hossein']='none'
NE_FinalSurvey.loc[NE_FinalSurvey.Supriya == 'Unsure', 'Supriya']='none'
NE_FinalSurvey.loc[NE_FinalSurvey.Mike == 'Unsure', 'Mike']='none'
NE_FinalSurvey.loc[NE_FinalSurvey.Kirti == 'Unsure', 'Kirti']='none'

NE_FinalSurvey["Vote"] = "PlaceHolder"

for idx in NE_FinalSurvey.index:
    # consensus
    if len(NE_FinalSurvey.loc[idx, people].unique())==1:
        NE_FinalSurvey.loc[idx, "Vote"]= "4 agree: "+ NE_FinalSurvey.loc[idx, people].unique()[0] 
        
    # Two types of votes:
    elif len(NE_FinalSurvey.loc[idx, people].unique())==2:
        answers_set=collections.Counter(NE_FinalSurvey.loc[idx, people].values)
        if answers_set['Single Crop']==3 or answers_set['Double Crop']==3:
            NE_FinalSurvey.loc[idx, "Vote"]="3 agree: " + answers_set.most_common(1)[0][0]
        else:
            NE_FinalSurvey.loc[idx, "Vote"]="disagreement"
    # otherwise, three types of votes or more.
    else:
        answers_set=collections.Counter(NE_FinalSurvey.loc[idx, people].values)
        NE_FinalSurvey.loc[idx, "Vote"]="disagreement"
#         if answers_set['none']==1:
#             del answers_set['none']
#             if len(answers_set)>1:
#                 NE_FinalSurvey.loc[idx, "Vote"]="2 agree - 1 disagree - 1 none"
#         else:
#             NE_FinalSurvey.loc[idx, "Vote"]="disagreement"
            
out_dir = "/Users/hn/Documents/01_research_data/NASA/parameters/NE_final_survey/"
out_name = out_dir + "pre_NE_FinalSurvey_EAD.csv"
NE_FinalSurvey.to_csv(out_name, index = False)

In [426]:
NE_FinalSurvey.groupby(['Vote'])['Vote'].count()

Vote
3 agree: Double Crop      39
3 agree: Single Crop     228
4 agree: Double Crop      15
4 agree: Single Crop    1394
disagreement             141
Name: Vote, dtype: int64

In [427]:
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Single Crop"].Hossein.unique())
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Single Crop"].Kirti.unique())
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Single Crop"].Supriya.unique())
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Single Crop"].Mike.unique())
print ("------------------------")
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Double Crop"].Hossein.unique())
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Double Crop"].Kirti.unique())
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Double Crop"].Supriya.unique())
print (NE_FinalSurvey[NE_FinalSurvey.Vote=="4 agree: Double Crop"].Mike.unique())

['Single Crop']
['Single Crop']
['Single Crop']
['Single Crop']
------------------------
['Double Crop']
['Double Crop']
['Double Crop']
['Double Crop']

In [428]:
1394+15

1409

In [439]:
228+39

267

# Drop agreements
so we can create Google Forms for final survey

In [441]:
NE_FinalSurvey.head(2)

,ID,Hossein,Supriya,Kirti,Mike,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county,Vote
0,104119_WSDA_SF_2016,Single Crop,Single Crop,Single Crop,Single Crop,alfalfa hay,center pivot,wsda,26,26.413875,2016/08/17 00:00:00,Adams,4 agree: Single Crop
1,51576_WSDA_SF_2016,Single Crop,Single Crop,Single Crop,Single Crop,alfalfa hay,center pivot,wsda,68,67.841870,2016/07/20 00:00:00,Adams,4 agree: Single Crop

In [442]:
NE_FinalSurvey.Vote.unique()

array(['4 agree: Single Crop', '3 agree: Double Crop', 'disagreement',
       '3 agree: Single Crop', '4 agree: Double Crop'], dtype=object)

In [443]:
easyVI_preMeeting_Agreement=NE_FinalSurvey[NE_FinalSurvey.Vote.isin(["4 agree: Single Crop", "4 agree: Double Crop"])]
easyVI_disagreements=NE_FinalSurvey[~NE_FinalSurvey.Vote.isin(["4 agree: Single Crop", "4 agree: Double Crop"])]

In [447]:
NE_FinalSurvey.shape[0]==easyVI_preMeeting_Agreement.shape[0]+easyVI_disagreements.shape[0]

True

In [448]:
out_dir = "/Users/hn/Documents/01_research_data/NASA/parameters/NE_final_survey/"

out_name = out_dir + "easyVI_preMeeting_Agreements.csv"
easyVI_preMeeting_Agreement.to_csv(out_name, index = False)

In [451]:
easyVI_disagreements.Vote.unique()

array(['3 agree: Double Crop', 'disagreement', '3 agree: Single Crop'],
      dtype=object)

# We need to have file names to create Google Forms,

In [453]:
Eshwar_Extensive=pd.read_csv(param_dir+"Eshwar_Extensive.csv")
print (Eshwar_Extensive.shape)
Eshwar_Extensive.head(2)

(6340, 16)

,Question_overall,ID,NDVI_TS_Name,corrected_RGB,TOA_RGB,latitude,longitude,Question Text,Text box Text,CropTyp,Irrigtn,DataSrc,Acres,ExctAcr,LstSrvD,county
0,1,104119_WSDA_SF_2016,AdamBenton2016_104119_WSDA_SF_2016.png,104119_WSDA_SF_2016_46.83273927_-118.91209151_...,104119_WSDA_SF_2016_46.83273927_-118.91209151_...,46.832739,-118.912092,How would you label this field?,Notes if you want to add any.,alfalfa hay,center pivot,wsda,26,26.413875,2016/08/17 00:00:00,Adams
1,2,51403_WSDA_SF_2016,AdamBenton2016_51403_WSDA_SF_2016.png,51403_WSDA_SF_2016_46.75090118_-118.9797641_co...,51403_WSDA_SF_2016_46.75090118_-118.9797641_TO...,46.750901,-118.979764,How would you label this field?,Notes if you want to add any.,alfalfa hay,center pivot,wsda,2,2.480750,2016/08/03 00:00:00,Adams

#### We need also to sort columns so that we can use old code for generating the Google Forms

In [ ]:
nonExpert_survey2_fields = pd.read_csv(NE_S2_dir+"nonExpert_survey2_fields.csv")

In [452]:

easyVI_disagreements_forFinalSurvey=pd.merge(easyVI_disagreements_forFinalSurvey,
                                             Eshwar_Extensive[,
                                             on=['ID'], how='left')

                                NDVI_TS_Name   latitude   longitude
0     AdamBenton2016_104119_WSDA_SF_2016.png  46.832739 -118.912092
1      AdamBenton2016_51403_WSDA_SF_2016.png  46.750901 -118.979764
2      AdamBenton2016_51545_WSDA_SF_2016.png  46.794645 -119.257949
3      AdamBenton2016_51576_WSDA_SF_2016.png  46.797982 -119.096528
4      AdamBenton2016_51590_WSDA_SF_2016.png  47.120771 -118.285102
...                                      ...        ...         ...
6335       Grant2017_104188_WSDA_SF_2017.png  47.114814 -119.688490
6336       Grant2017_106509_WSDA_SF_2017.png  47.136699 -119.560875
6337       Grant2017_108383_WSDA_SF_2017.png  47.133688 -119.556640
6338        Grant2017_98716_WSDA_SF_2017.png  47.100403 -119.563009
6339        Grant2017_99604_WSDA_SF_2017.png  47.084810 -119.732104

[6340 rows x 3 columns]

In [ ]:
out_name = out_dir + "easyVI_disagreements_forFinalSurvey.csv"
easyVI_disagreements.to_csv(out_name, index = False)